fn main() {
    // The ACL needs an explicit application manifest: without it no app
    // command is permissionable, and every invoke from the remote UI dies
    // with "not allowed" (work-browser-tabs handoff). Listing the commands
    // here autogenerates `allow-<name>` / `deny-<name>` permissions which
    // the capability files can then reference.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            "chrome_layers",
            "btab_navigate",
            "btab_bounds",
            "btab_visibility",
            "btab_back",
            "btab_forward",
            "btab_reload",
            "btab_meta",
            "btab_screenshot",
            "btab_preview",
            "btab_print",
            "btab_zoom",
            "btab_set_zoom",
            "btab_find",
            "btab_cdp_call",
            "btab_cdp_events",
            "btab_close",
            "btab_clear_app_data",
            "btab_open_external",
            "btab_annotate_mode",
            "btab_annotate_clear",
            "btab_annotate_state",
            "btab_annotate_overlay",
            "btab_set_prefs",
            "btab_clear_data",
            "btab_download_dir",
            "btab_set_download_dir",
            "btab_set_ask_download",
            "btab_open_path",
            "btab_reveal_path",
            "btab_set_permission_policy",
            "btab_permission_answer",
            "btab_set_scripts",
            "btab_set_developer_mode",
            "lab_open",
            "lab_navigate",
            "lab_back",
            "lab_forward",
            "lab_reload",
            "lab_current_url",
            "computer_displays",
            "computer_windows",
            "computer_call",
            "computer_set_grants",
            "computer_preview",
            "computerlab_open",
            "computer_embed",
            "computer_unembed",
            "disk_report",
            "disk_compact",
            "disk_compact_dry_run",
            "clean_list",
            "clean_apply",
            "wslconfig_read",
            "wslconfig_write",
        ])),
    )
    .expect("failed to run tauri-build");
}
