package climemory

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func seed(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestTiersAreDeclaredNotInferred: the pane's capability comes from the
// catalog, so a CLI never gains an editor because a folder happened to exist.
func TestTiersAreDeclaredNotInferred(t *testing.T) {
	want := map[string]Tier{
		"claude-code": TierEditable,
		"hermes":      TierEditable,
		"muse":        TierEditable,
		"omp":         TierEditable,
		"grok":        TierReadOnly,
		"codex":       TierReadOnly,
		"pi":          TierNone,
		"opencode":    TierNone,
		"agy":         TierUnknown,
	}
	if len(Supported()) != len(want) {
		t.Fatalf("catalog has %d CLIs, the table has %d", len(Supported()), len(want))
	}
	for cli, tier := range want {
		rep, err := Describe(cli, Paths{Home: t.TempDir()})
		if err != nil {
			t.Fatalf("%s: %v", cli, err)
		}
		if rep.Tier != tier {
			t.Errorf("%s: tier %q, want %q", cli, rep.Tier, tier)
		}
		if tier == TierNone || tier == TierUnknown {
			if rep.Note == "" {
				t.Errorf("%s: a CLI with no memory owes the reader one line", cli)
			}
			if len(rep.Stores) != 0 {
				t.Errorf("%s: no memory means no stores, got %d", cli, len(rep.Stores))
			}
		}
	}
}

// TestReadOnlyTierRefusesWrites: Grok's and Codex's indexes are theirs.
func TestReadOnlyTierRefusesWrites(t *testing.T) {
	for _, cli := range []string{"grok", "codex"} {
		home := t.TempDir()
		var dir string
		switch cli {
		case "grok":
			dir = filepath.Join(home, ".grok", "memory-v2", "global")
		case "codex":
			dir = filepath.Join(home, ".codex", "memories")
		}
		seed(t, filepath.Join(dir, "MEMORY.md"), "# index\n\n> Generated by Grok. Do not edit this file directly.\n")
		seed(t, filepath.Join(dir, "testing.md"), "# testing\n\nUse make ci-scoped.\n")
		p := Paths{Home: home}
		if _, err := List(cli, p, "global"); err != nil {
			t.Fatalf("%s list: %v", cli, err)
		}
		if err := Write(cli, p, "global", "testing.md", "changed"); err == nil {
			t.Errorf("%s: a write must be refused", cli)
		}
		err := Delete(cli, p, "global", "testing.md")
		if err == nil {
			t.Errorf("%s: a delete must be refused", cli)
		} else if cli == "grok" && !strings.Contains(err.Error(), "grok memory clear") {
			t.Errorf("grok: the refusal should name the vendor command, got %q", err)
		}
		if _, err := os.Stat(filepath.Join(dir, "testing.md")); err != nil {
			t.Errorf("%s: the file must survive a refused delete", cli)
		}
	}
}

// TestEditableTierListsReadsWritesAndDeletes, on a Claude Code memory folder
// shaped like the real one.
func TestEditableTierListsReadsWritesAndDeletes(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	dir := filepath.Join(home, ".claude", "projects", slugify(cwd), "memory")
	seed(t, filepath.Join(dir, "MEMORY.md"), "- [Role](user-role.md) — who the user is\n")
	seed(t, filepath.Join(dir, "user-role.md"), "---\nname: user-role\ndescription: The owner ships PiCode\nmetadata:\n  type: user\n---\n\nThe owner runs the repo.\n")
	p := Paths{Home: home, Cwd: cwd}

	items, err := List("claude-code", p, "workspace")
	if err != nil {
		t.Fatal(err)
	}
	if len(items) != 2 {
		t.Fatalf("want 2 items, got %d: %#v", len(items), items)
	}
	if !items[0].Index {
		t.Fatalf("the index sorts first, got %#v", items[0])
	}
	var fact Item
	for _, item := range items {
		if item.ID == "user-role.md" {
			fact = item
		}
	}
	if fact.Kind != "user" {
		t.Errorf("frontmatter type not read: %#v", fact)
	}
	if fact.Summary != "The owner ships PiCode" {
		t.Errorf("description not read: %q", fact.Summary)
	}

	body, err := Read("claude-code", p, "workspace", "user-role.md")
	if err != nil || !strings.Contains(body, "The owner runs the repo.") {
		t.Fatalf("read: %v %q", err, body)
	}
	if err := Write("claude-code", p, "workspace", "user-role.md", "changed\n"); err != nil {
		t.Fatal(err)
	}
	if got, _ := os.ReadFile(filepath.Join(dir, "user-role.md")); string(got) != "changed\n" {
		t.Fatalf("write did not land: %q", got)
	}
	if err := Delete("claude-code", p, "workspace", "user-role.md"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "user-role.md")); !os.IsNotExist(err) {
		t.Fatal("delete did not remove the file")
	}
	// The index is not deletable: it is the map to everything else.
	if err := Delete("claude-code", p, "workspace", "MEMORY.md"); err == nil {
		t.Fatal("the index must not be deletable")
	}
}

// TestClaudeSlugMatchesTheRealRule, checked against directory names Claude Code
// itself created on the owner's machine (2026-09-20).
func TestClaudeSlugMatchesTheRealRule(t *testing.T) {
	for path, want := range map[string]string{
		"/home/goat/picode": "-home-goat-picode",
		"/home/goat/picode/.claude/worktrees/feat/inbox-tabs": "-home-goat-picode--claude-worktrees-feat-inbox-tabs",
		"/home/goat/agentdeck/data/workspaces/1fcd27d18c59":   "-home-goat-agentdeck-data-workspaces-1fcd27d18c59",
	} {
		if got := slugify(path); got != want {
			t.Errorf("slugify(%q) = %q, want %q", path, got, want)
		}
	}
}

// TestWorktreesShareTheRepositoryMemory: Claude Code keys its folder on the
// repository, so a PiCode worktree must read the same memory as its main
// checkout instead of an empty one.
func TestWorktreesShareTheRepositoryMemory(t *testing.T) {
	home := t.TempDir()
	repo := filepath.Join(t.TempDir(), "project")
	tree := filepath.Join(repo, ".worktrees", "feature")
	if err := os.MkdirAll(filepath.Join(repo, ".git", "worktrees", "feature"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(tree, 0o755); err != nil {
		t.Fatal(err)
	}
	seed(t, filepath.Join(tree, ".git"), "gitdir: "+filepath.Join(repo, ".git", "worktrees", "feature")+"\n")
	dir := filepath.Join(home, ".claude", "projects", slugify(repo), "memory")
	seed(t, filepath.Join(dir, "MEMORY.md"), "- one line\n")

	rep, err := Describe("claude-code", Paths{Home: home, Cwd: tree})
	if err != nil {
		t.Fatal(err)
	}
	if !rep.Stores[0].Exists || rep.Stores[0].Path != dir {
		t.Fatalf("a worktree must resolve to the repository's memory, got %#v", rep.Stores[0])
	}
}

// TestGrokWorkspaceIsMatchedOrRefused: Grok hashes the workspace path into the
// folder name. PiCode matches on the name and says unknown when the match is
// ambiguous rather than showing another project's memory.
func TestGrokWorkspaceIsMatchedOrRefused(t *testing.T) {
	home := t.TempDir()
	base := filepath.Join(home, ".grok", "memory-v2", "workspaces")
	cwd := filepath.Join(t.TempDir(), "picode")
	if err := os.MkdirAll(cwd, 0o755); err != nil {
		t.Fatal(err)
	}
	seed(t, filepath.Join(base, "picode-e1f77c5c", "MEMORY.md"), "# index\n")
	seed(t, filepath.Join(base, "other-1234abcd", "MEMORY.md"), "# index\n")
	rep, err := Describe("grok", Paths{Home: home, Cwd: cwd})
	if err != nil {
		t.Fatal(err)
	}
	ws := rep.Stores[1]
	if !ws.Resolved || !strings.HasSuffix(ws.Path, "picode-e1f77c5c") {
		t.Fatalf("want the matching folder, got %#v", ws)
	}

	// A second folder with the same workspace name is ambiguous.
	seed(t, filepath.Join(base, "picode-99999999", "MEMORY.md"), "# index\n")
	rep, _ = Describe("grok", Paths{Home: home, Cwd: cwd})
	ws = rep.Stores[1]
	if ws.Resolved || ws.Note == "" {
		t.Fatalf("an ambiguous match must be reported, got %#v", ws)
	}
	if _, err := List("grok", Paths{Home: home, Cwd: cwd}, "workspace"); err == nil {
		t.Fatal("listing an unresolved store must refuse")
	}
}

// TestCustomMemoryDirectoryIsHonored: a user who moved the folder in settings
// must see the folder they moved it to.
func TestCustomMemoryDirectoryIsHonored(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	// Inside the user's own home: the setting is honoured there and bounded
	// outside it (TestRelocatedStoreStaysInsideTheHome).
	custom := filepath.Join(home, "notes")
	seed(t, filepath.Join(custom, "MEMORY.md"), "- moved\n")
	p := Paths{Home: home, Cwd: cwd, Setting: func(cli, key string) (string, bool) {
		if cli == "claude-code" && key == "autoMemoryDirectory" {
			return custom, true
		}
		return "", false
	}}
	rep, err := Describe("claude-code", p)
	if err != nil {
		t.Fatal(err)
	}
	if rep.Stores[0].Path != custom || !rep.Stores[0].Exists {
		t.Fatalf("want the moved folder, got %#v", rep.Stores[0])
	}
}

// TestReadStaysInsideTheStore: no traversal, no symlink out.
func TestReadStaysInsideTheStore(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	dir := filepath.Join(home, ".claude", "projects", slugify(cwd), "memory")
	seed(t, filepath.Join(dir, "MEMORY.md"), "- index\n")
	secret := filepath.Join(home, "secret.md")
	seed(t, secret, "not a memory\n")
	if err := os.Symlink(secret, filepath.Join(dir, "link.md")); err != nil {
		t.Skip("symlinks unavailable")
	}
	p := Paths{Home: home, Cwd: cwd}
	for _, id := range []string{"../../../secret.md", "link.md", "/etc/passwd"} {
		if body, err := Read("claude-code", p, "workspace", id); err == nil {
			t.Errorf("%s was readable: %q", id, body)
		}
	}
}

// TestSecretShapesAreMaskedOnRead. The file keeps what the CLI wrote; the pane
// does not echo a credential back.
func TestSecretShapesAreMaskedOnRead(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	dir := filepath.Join(home, ".claude", "projects", slugify(cwd), "memory")
	raw := "The deploy key is ghp_abcdefghijklmnopqrstuvwxyz012345 and the api key sk-ant-abcdefghijklmnopqrstuvwxyz.\nOrdinary prose about sk and about bearer tokens stays.\n"
	seed(t, filepath.Join(dir, "keys.md"), raw)
	body, err := Read("claude-code", Paths{Home: home, Cwd: cwd}, "workspace", "keys.md")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(body, "ghp_abcdefghijklmnopqrstuvwxyz012345") || strings.Contains(body, "sk-ant-abcdefghijklmnopqrstuvwxyz") {
		t.Fatalf("a credential was echoed: %q", body)
	}
	if !strings.Contains(body, "Ordinary prose about sk and about bearer tokens stays.") {
		t.Fatalf("prose was over-masked: %q", body)
	}
	if got, _ := os.ReadFile(filepath.Join(dir, "keys.md")); string(got) != raw {
		t.Fatal("masking must not change the file")
	}
}

// TestGeneratedFileIsNeverWritten: even in the editable tier, a file that says
// the CLI generates it is not PiCode's to rewrite. The guard reads the file on
// disk — it used to read the replacement, so a generated file was overwritten
// with clean text and a clean file could not be given a banner
// (adversarial review, 2026-09-20).
func TestGeneratedFileIsNeverWritten(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	dir := filepath.Join(home, ".claude", "projects", slugify(cwd), "memory")
	seed(t, filepath.Join(dir, "MEMORY.md"), "- index\n")
	seed(t, filepath.Join(dir, "generated.md"), "# index\n\n> Generated by Grok. Do not edit this file directly.\n")
	p := Paths{Home: home, Cwd: cwd}

	if err := Write("claude-code", p, "workspace", "generated.md", "clean text\n"); err == nil {
		t.Fatal("a file that says it is generated must not be overwritten")
	}
	if body, _ := os.ReadFile(filepath.Join(dir, "generated.md")); !strings.Contains(string(body), "Do not edit") {
		t.Fatal("the generated file was overwritten")
	}
	// A file that is not generated is writable, whatever the new text says.
	if err := Write("claude-code", p, "workspace", "MEMORY.md", "- index\n- and a note\n"); err != nil {
		t.Fatalf("a legitimate write was refused: %v", err)
	}
}

// TestWorkspaceStoreNeedsAWorkspace: no workspace, no guess.
func TestWorkspaceStoreNeedsAWorkspace(t *testing.T) {
	rep, err := Describe("claude-code", Paths{Home: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	if rep.Stores[0].Resolved || rep.Stores[0].Note == "" {
		t.Fatalf("want an unresolved store with a reason, got %#v", rep.Stores[0])
	}
}

// TestOmpSaysMemoryIsOffRatherThanNamingAFolderItGuessed.
func TestOmpSaysMemoryIsOffRatherThanNamingAFolderItGuessed(t *testing.T) {
	rep, err := Describe("omp", Paths{Home: t.TempDir(), Cwd: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	store := rep.Stores[0]
	if store.Resolved || !strings.Contains(store.Note, "Settings") {
		t.Fatalf("want an unresolved store pointing at the setting, got %#v", store)
	}
	if rep.Toggle != "memory.backend" {
		t.Fatalf("the toggle must name the CLI's own key, got %q", rep.Toggle)
	}
}

// TestEveryToggleIsARealSettingsKey ties the two panes together: the switch the
// Memory pane offers must be a key the settings driver actually writes.
func TestEveryToggleIsARealSettingsKey(t *testing.T) {
	keys := map[string][]string{
		"claude-code": {"autoMemoryEnabled"},
		"codex":       {"features.memories", "memories.generate_memories", "memories.use_memories"},
		"hermes":      {"memory.memory_enabled", "memory.user_profile_enabled"},
		"omp":         {"memory.backend"},
	}
	for _, cli := range Supported() {
		s := For(cli)
		if s.toggle == "" {
			continue
		}
		declared, ok := keys[cli]
		if !ok {
			t.Errorf("%s declares a toggle %q with no settings keys listed here", cli, s.toggle)
			continue
		}
		found := false
		for _, key := range declared {
			if key == s.toggle {
				found = true
			}
		}
		if !found {
			t.Errorf("%s: toggle %q is not one of its settings keys %v", cli, s.toggle, declared)
		}
	}
}

// TestMissingItemDoesNotEchoTheFilesystem: the reader gets the name they
// asked for, not an absolute path from a raw syscall error.
func TestMissingItemDoesNotEchoTheFilesystem(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	dir := filepath.Join(home, ".claude", "projects", slugify(cwd), "memory")
	seed(t, filepath.Join(dir, "MEMORY.md"), "- index\n")
	_, err := Read("claude-code", Paths{Home: home, Cwd: cwd}, "workspace", "../../.codex/config.toml")
	if err == nil {
		t.Fatal("want a refusal")
	}
	if strings.Contains(err.Error(), home) || strings.Contains(err.Error(), "stat ") {
		t.Fatalf("the error echoes the filesystem: %q", err)
	}
	if !strings.Contains(err.Error(), "config.toml") {
		t.Fatalf("the error should name what was asked for: %q", err)
	}
}

// TestNotesAreOneLineOfStateNotAnEssay: chrome carries state and the next
// action. A note that explains how a store is built belongs in the
// architecture doc (.pi/skills/uiux-review, instant FAIL).
func TestNotesAreOneLineOfStateNotAnEssay(t *testing.T) {
	for _, cli := range Supported() {
		note := For(cli).note
		if note == "" {
			continue
		}
		if len(note) > 120 {
			t.Errorf("%s: note is %d characters, too long for chrome: %q", cli, len(note), note)
		}
		for _, word := range []string{"database", "SQLite", "sqlite", "git baseline", "index in a"} {
			if strings.Contains(note, word) {
				t.Errorf("%s: note explains the mechanism (%q), which belongs in the architecture doc: %q", cli, word, note)
			}
		}
	}
}

// TestWriteCannotEscapeThroughASymlinkedDirectory is the regression for the
// containment hole the adversarial review found: within() resolved the target
// file, which does not exist on a create, so the check was skipped and a write
// through a symlinked subdirectory landed outside the store. Delete was safe
// only because its target existed.
func TestWriteCannotEscapeThroughASymlinkedDirectory(t *testing.T) {
	home, outside := t.TempDir(), t.TempDir()
	dir := filepath.Join(home, ".hermes", "memories")
	seed(t, filepath.Join(dir, "MEMORY.md"), "index\n")
	if err := os.Symlink(outside, filepath.Join(dir, "link")); err != nil {
		t.Skip("symlinks unavailable")
	}
	seed(t, filepath.Join(outside, "victim.md"), "keep\n")
	p := Paths{Home: home}

	for _, id := range []string{"link/pwn.md", "link/nested/pwn.md", "./link/./pwn.md"} {
		if err := Write("hermes", p, "global", id, "escaped\n"); err == nil {
			t.Errorf("%s: a write outside the store was allowed", id)
		}
		if _, err := os.Stat(filepath.Join(outside, "pwn.md")); err == nil {
			t.Fatalf("%s: the file was created outside the store", id)
		}
	}
	if err := Delete("hermes", p, "global", "link/victim.md"); err == nil {
		t.Error("a delete outside the store was allowed")
	}
	if _, err := os.Stat(filepath.Join(outside, "victim.md")); err != nil {
		t.Error("a file outside the store was removed")
	}
	// A real memory inside the store is still writable.
	if err := Write("hermes", p, "global", "USER.md", "fine\n"); err != nil {
		t.Fatalf("a legitimate write was refused: %v", err)
	}
}

// TestMaskCoversTheShapesThatMatterAndSparesProse. The unanchored `sk-` rule
// destroyed ordinary words, and several common credential shapes sailed
// through (adversarial review, 2026-09-20).
func TestMaskCoversTheShapesThatMatterAndSparesProse(t *testing.T) {
	secrets := []string{
		"aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
		"DB_PASSWORD=correct-horse-battery-staple",
		"api_key: 7f3a91c0deadbeefcafe1234567890ab",
		"https://deploy:s3cr3t-p4ssw0rd@git.example.com/repo.git",
		"postgres://app:Tr0ub4dor3@db.internal:5432/prod",
		"sk_live_51H8xQ2KZabcdefghijklmnop",
		"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",
		"npm_AbCdEfGhIjKlMnOpQrStUvWxYz0123456789",
		"https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX",
		"-----BEGIN PGP PRIVATE KEY BLOCK-----\nlQdGBGX\n-----END PGP PRIVATE KEY BLOCK-----",
		"-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAA\n",
	}
	for _, raw := range secrets {
		got := mask(raw)
		if got == raw {
			t.Errorf("not masked: %q", firstLineOf(raw))
		}
	}
	// Prose must come through untouched.
	for _, prose := range []string{
		"risk-assessment-and-mitigation is the next milestone",
		"see the task-management-and-tracking board",
		"/home/user/notes/disk-encryption-rollout-plan.md",
		"the desk-setup-documentation-2026 page moved",
		"ask about the key and the password policy",
	} {
		if got := mask(prose); got != prose {
			t.Errorf("prose was masked:\n  in:  %q\n  out: %q", prose, got)
		}
	}
	// The assignment keeps its name, so the line still says what was there.
	if got := mask("api_key: 7f3a91c0deadbeefcafe1234567890ab"); !strings.HasPrefix(got, "api_key: ") {
		t.Errorf("the name should survive: %q", got)
	}
}

func firstLineOf(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// TestSummaryIsMaskedBeforeItIsClipped: clipping first cut a credential into a
// shape the regex no longer matched, and the prefix was published.
func TestSummaryIsMaskedBeforeItIsClipped(t *testing.T) {
	long := strings.Repeat("x", summaryRunes-10) + " AKIAIOSFODNN7EXAMPLE tail"
	_, summary, _ := describeHead(long)
	if strings.Contains(summary, "AKIA") {
		t.Fatalf("a credential survived the clip: %q", summary)
	}
}

// TestGrokMatchIsAnchoredOnTheHash: a bare prefix made `picode` match
// `picode-companion-4a503445`, so the owner's own repository always reported
// "several folders match" and the pane was dark (adversarial review).
func TestGrokMatchIsAnchoredOnTheHash(t *testing.T) {
	home := t.TempDir()
	base := filepath.Join(home, ".grok", "memory-v2", "workspaces")
	cwd := filepath.Join(t.TempDir(), "picode")
	if err := os.MkdirAll(cwd, 0o755); err != nil {
		t.Fatal(err)
	}
	seed(t, filepath.Join(base, "picode-e1f77c5c", "MEMORY.md"), "# index\n")
	seed(t, filepath.Join(base, "picode-companion-4a503445", "MEMORY.md"), "# index\n")
	rep, err := Describe("grok", Paths{Home: home, Cwd: cwd})
	if err != nil {
		t.Fatal(err)
	}
	ws := rep.Stores[1]
	if !ws.Resolved || !strings.HasSuffix(ws.Path, "picode-e1f77c5c") {
		t.Fatalf("want the hashed folder for this workspace, got %#v", ws)
	}
}

// TestRelocatedStoreStaysInsideTheHome: `autoMemoryDirectory` is text the
// settings pane writes, and the memory pane used it as its root unchecked.
func TestRelocatedStoreStaysInsideTheHome(t *testing.T) {
	home, cwd := t.TempDir(), t.TempDir()
	setting := func(dir string) func(string, string) (string, bool) {
		return func(cli, key string) (string, bool) {
			if cli == "claude-code" && key == "autoMemoryDirectory" {
				return dir, true
			}
			return "", false
		}
	}
	for _, bad := range []string{"/etc", "/proc/self", "relative/path", ".."} {
		p := Paths{Home: home, Cwd: cwd, Setting: setting(bad)}
		rep, err := Describe("claude-code", p)
		if err != nil {
			t.Fatal(err)
		}
		if rep.Stores[0].Resolved || rep.Stores[0].Note == "" {
			t.Errorf("%s was accepted as a memory folder: %#v", bad, rep.Stores[0])
		}
		if _, err := Read("claude-code", p, "workspace", "passwd"); err == nil {
			t.Errorf("%s allowed a read", bad)
		}
	}
	// A folder the user moved inside their own home is still honoured.
	inside := filepath.Join(home, "notes")
	seed(t, filepath.Join(inside, "MEMORY.md"), "- moved\n")
	rep, err := Describe("claude-code", Paths{Home: home, Cwd: cwd, Setting: setting(inside)})
	if err != nil {
		t.Fatal(err)
	}
	if rep.Stores[0].Path != inside || !rep.Stores[0].Exists {
		t.Fatalf("want the moved folder, got %#v", rep.Stores[0])
	}
}
