ALTER TABLE webapps ADD COLUMN start_url TEXT NOT NULL DEFAULT '';
ALTER TABLE webapps ADD COLUMN scope TEXT NOT NULL DEFAULT '';
ALTER TABLE webapps ADD COLUMN display TEXT NOT NULL DEFAULT '';
ALTER TABLE webapps ADD COLUMN theme_color TEXT NOT NULL DEFAULT '';
