#!/usr/bin/env node
// docs-check — the parity gate (make docs-check). Verifies that every image
// the docs ship was generated by the capture pipeline from the CURRENT UI:
//
//   1. manifest.json exists, lists every expected surface, and each surface's
//      input hash matches its current component/server/fixture dependencies.
//      Tests and unrelated handlers do not trip the gate.
//   2. every declared surface file exists and its sha256 matches the manifest
//      — hand-edited or half-regenerated images fail here.
//
// Byte-level re-capture diffing lands in CI once capture determinism is
// proven on the runner; this gate is the always-on floor.

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { screenshotInputFailures } from "./lib/docs-surfaces.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const imgDir = join(root, "docs-site", "img");

// Capture freshness is advisory unless --strict / DOCS_STRICT=1 (ADR-0086):
// a stale fingerprint used to fail `make ci` for every CSS change, and the
// recapture it demanded produced binary conflicts between parallel
// sessions. `make deploy` runs the strict form and recaptures when it says
// so (ADR-0105); a committed image that was edited by hand still fails
// everywhere.
const strict = process.argv.includes("--strict") || process.env.DOCS_STRICT === "1";
const fails = [];
const stale = [];
const manifestPath = join(imgDir, "manifest.json");
if (!existsSync(manifestPath)) {
  fails.push("manifest.json missing — run `make docs-shots`");
} else {
  const m = JSON.parse(readFileSync(manifestPath, "utf8"));
  stale.push(...screenshotInputFailures(root, m));
  for (const [name, s] of Object.entries(m.surfaces ?? {})) {
    const p = join(imgDir, s.file);
    if (!existsSync(p)) {
      fails.push(`${name}: ${s.file} missing`);
      continue;
    }
    const actual = createHash("sha256").update(readFileSync(p)).digest("hex");
    if (actual !== s.sha256) {
      fails.push(`${name}: ${s.file} hash mismatch — edited by hand? (run \`make docs-shots\`)`);
    }
  }
  if (!Object.keys(m.surfaces ?? {}).length) fails.push("manifest lists no surfaces");
}

// ── generated docs artifact: openapi.json ─────────────────────────────
// Same parity rule as the screenshots: the committed artifact must be
// byte-identical to what the generator produces from the CURRENT tree.
// llms.txt is not here: it is produced by `make docs`/`make deploy` and is
// not committed at all (ADR-0125), so there is no copy to be stale.
const openapiPath = join(root, "docs-site", "public", "api", "openapi.json");
if (!existsSync(openapiPath)) {
  fails.push("docs-site/public/api/openapi.json missing — run `make openapi`");
} else {
  try {
    const fresh = execFileSync("go", ["run", "./cmd/picode-openapi"], {
      cwd: root,
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024,
    });
    if (fresh !== readFileSync(openapiPath, "utf8")) {
      fails.push("openapi.json is stale (server routes changed) — run `make openapi`");
    }
  } catch (e) {
    fails.push(`openapi regeneration failed: ${String(e.message).slice(0, 200)}`);
  }
}

// ── tutorial videos: fast integrity floor, never capture or render ─────
// Per-surface freshness is an explicit maintenance audit (`make
// docs-videos-fresh`). CI still refuses missing/tampered MP4s and changes to
// a composition or still that was actually rendered.
try {
  execFileSync("node", [join(root, "scripts", "docs-video-manifest.mjs"), "--check"], {
    encoding: "utf8",
  });
  console.log("videos integrity ok");
} catch (e) {
  fails.push(String(e.stderr || e.message).trim().slice(0, 400));
}

// ── living docs: the index and the cross-references ───────────────────
// An adversarial pass (2026-09-21) found each of these wrong in a way no
// gate could see: eight ADRs the index still called "proposed" after the
// owner accepted them, one subsystem file nothing linked to, and three
// relative links that resolved to nowhere. All three are cheap to read
// from the tree, so none of them needs a human to notice again.
const decisionsDir = join(root, "docs", "decisions");
const indexPath = join(decisionsDir, "README.md");
if (existsSync(indexPath)) {
  const index = readFileSync(indexPath, "utf8");
  const rows = new Map();
  for (const line of index.split("\n")) {
    const m = /^\| \[(\d{4})\]\(([^)]+)\)/.exec(line);
    if (!m) continue;
    const cells = line.split("|");
    rows.set(m[1], { file: m[2], status: (cells[cells.length - 2] ?? "").trim() });
  }
  const files = readdirSync(decisionsDir).filter((f) => /^\d{4}-.*\.md$/.test(f)).sort();
  for (const f of files) {
    const n = f.slice(0, 4);
    const row = rows.get(n);
    if (!row) {
      fails.push(`ADR ${n} has no row in docs/decisions/README.md — \`make adr\` appends one`);
      continue;
    }
    if (row.file !== f) fails.push(`ADR ${n}: the index links ${row.file}, the file is ${f}`);
    // The index carries the CURRENT status, so "superseded by …" and
    // "amended …" are richer than the file's header and stay. The one
    // direction that is always wrong is an accepted decision the index
    // still presents as a proposal.
    const own = /^\s*-\s*\*\*Status\*\*?:?\*?\*?:?\s*(\w+)/im.exec(readFileSync(join(decisionsDir, f), "utf8"));
    if (own && own[1].toLowerCase() === "accepted" && /^proposed\b/i.test(row.status)) {
      fails.push(`ADR ${n} is accepted in its own file but "proposed" in the index — update docs/decisions/README.md`);
    }
  }
  for (const n of rows.keys()) {
    if (!files.some((f) => f.startsWith(n))) fails.push(`docs/decisions/README.md has a row for ADR ${n} with no file`);
  }
}

// docs/architecture.md only links (ADR-0105). A subsystem file it does not
// name is documentation nobody can find from the index.
const archDir = join(root, "docs", "architecture");
const archIndexPath = join(root, "docs", "architecture.md");
if (existsSync(archDir) && existsSync(archIndexPath)) {
  const linked = new Set(
    [...readFileSync(archIndexPath, "utf8").matchAll(/architecture\/([a-z0-9-]+\.md)/g)].map((m) => m[1]),
  );
  for (const f of readdirSync(archDir).filter((f) => f.endsWith(".md")).sort()) {
    if (!linked.has(f)) fails.push(`docs/architecture/${f} is not linked from docs/architecture.md`);
  }
  for (const f of linked) {
    if (!existsSync(join(archDir, f))) fails.push(`docs/architecture.md links architecture/${f}, which does not exist`);
  }
}

// Relative Markdown links inside docs/ must resolve. docs/handoff.md is the
// exception: it is generated by `make handoff` and is not in git (ADR-0123).
function markdownFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    if (e.name === "node_modules" || e.name === ".vitepress") return [];
    const p = join(dir, e.name);
    return e.isDirectory() ? markdownFiles(p) : e.name.endsWith(".md") ? [p] : [];
  });
}
for (const file of markdownFiles(join(root, "docs"))) {
  for (const m of readFileSync(file, "utf8").matchAll(/\]\(([^)\s#]+)(?:#[^)]*)?\)/g)) {
    const target = m[1];
    if (/^(?:[a-z]+:|\/|#)/i.test(target) || target.endsWith("handoff.md")) continue;
    if (!existsSync(resolve(dirname(file), target))) {
      fails.push(`${relative(root, file)}: broken relative link ${target}`);
    }
  }
}

if (stale.length) {
  if (strict) fails.push(...stale);
  else {
    console.warn("docs-check: public captures are stale (`make deploy` recaptures; or run `make docs-shots`):");
    for (const f of stale) console.warn("  - " + f);
  }
}
if (fails.length) {
  console.error("docs-check FAILED:");
  for (const f of fails) console.error("  - " + f);
  process.exit(1);
}
console.log(stale.length ? "docs-check ok (captures stale, advisory)" : "docs-check ok: current images/generated docs and video integrity verified");
