#!/usr/bin/env node
// docs-check — the parity gate (make docs-check). Verifies that every image
// the docs ship was generated by the capture pipeline from the CURRENT UI:
//
//   1. manifest.json exists, lists every expected surface, and each surface's
//      input hash matches its current component/server/fixture dependencies.
//      Tests and unrelated handlers do not trip the gate.
//   2. every declared surface file exists and its sha256 matches the manifest
//      — hand-edited or half-regenerated images fail here.
//
// Byte-level re-capture diffing lands in CI once capture determinism is
// proven on the runner; this gate is the always-on floor.

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { screenshotInputFailures } from "./lib/docs-surfaces.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const imgDir = join(root, "www", "img");

const fails = [];
const manifestPath = join(imgDir, "manifest.json");
if (!existsSync(manifestPath)) {
  fails.push("manifest.json missing — run `make docs-shots`");
} else {
  const m = JSON.parse(readFileSync(manifestPath, "utf8"));
  fails.push(...screenshotInputFailures(root, m));
  for (const [name, s] of Object.entries(m.surfaces ?? {})) {
    const p = join(imgDir, s.file);
    if (!existsSync(p)) {
      fails.push(`${name}: ${s.file} missing`);
      continue;
    }
    const actual = createHash("sha256").update(readFileSync(p)).digest("hex");
    if (actual !== s.sha256) {
      fails.push(`${name}: ${s.file} hash mismatch — edited by hand? (run \`make docs-shots\`)`);
    }
  }
  if (!Object.keys(m.surfaces ?? {}).length) fails.push("manifest lists no surfaces");
}

// ── generated docs artifacts: openapi.json + llms.txt ──────────────────
// Same parity rule as the screenshots: the committed artifact must be
// byte-identical to what the generator produces from the CURRENT tree.
const openapiPath = join(root, "www", "public", "api", "openapi.json");
if (!existsSync(openapiPath)) {
  fails.push("www/public/api/openapi.json missing — run `make openapi`");
} else {
  try {
    const fresh = execFileSync("go", ["run", "./cmd/picode-openapi"], {
      cwd: root,
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024,
    });
    if (fresh !== readFileSync(openapiPath, "utf8")) {
      fails.push("openapi.json is stale (server routes changed) — run `make openapi`");
    }
  } catch (e) {
    fails.push(`openapi regeneration failed: ${String(e.message).slice(0, 200)}`);
  }
}

try {
  execFileSync("node", [join(root, "scripts", "docs-llms.mjs"), "--check"], {
    encoding: "utf8",
  });
} catch (e) {
  fails.push(String(e.stderr || e.message).trim().slice(0, 300));
}

// ── tutorial videos: fast integrity floor, never capture or render ─────
// Per-surface freshness is an explicit maintenance audit (`make
// docs-videos-fresh`). CI still refuses missing/tampered MP4s and changes to
// a composition or still that was actually rendered.
try {
  execFileSync("node", [join(root, "scripts", "docs-video-manifest.mjs"), "--check"], {
    encoding: "utf8",
  });
  console.log("videos integrity ok");
} catch (e) {
  fails.push(String(e.stderr || e.message).trim().slice(0, 400));
}

if (fails.length) {
  console.error("docs-check FAILED:");
  for (const f of fails) console.error("  - " + f);
  process.exit(1);
}
console.log("docs-check ok: current images/generated docs and video integrity verified");
