#!/usr/bin/env node
// docs-check — the parity gate (make docs-check). Verifies that every image
// the docs ship was generated by the capture pipeline from the CURRENT UI:
//
//   1. manifest.json exists, lists surfaces, and its uiTreeHash matches HEAD
//      (hash of web/src + internal/server + fixture + pipeline trees). A UI
//      change without `make docs-shots` fails here; changelog/handoff commits
//      do not trip it.
//   2. every declared surface file exists and its sha256 matches the manifest
//      — hand-edited or half-regenerated images fail here.
//
// Byte-level re-capture diffing lands in CI once capture determinism is
// proven on the runner; this gate is the always-on floor.

import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { uiTreeHash } from "./lib/uitree.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const imgDir = join(root, "www", "img");

const fails = [];
const manifestPath = join(imgDir, "manifest.json");
if (!existsSync(manifestPath)) {
  fails.push("manifest.json missing — run `make docs-shots`");
} else {
  const m = JSON.parse(readFileSync(manifestPath, "utf8"));
  if (m.uiTreeHash !== uiTreeHash(root)) {
    fails.push(
      `manifest is stale: UI tree changed since capture (${String(m.gitSha).slice(0, 10)}) — run \`make docs-shots\``,
    );
  }
  for (const [name, s] of Object.entries(m.surfaces ?? {})) {
    const p = join(imgDir, s.file);
    if (!existsSync(p)) {
      fails.push(`${name}: ${s.file} missing`);
      continue;
    }
    const actual = createHash("sha256").update(readFileSync(p)).digest("hex");
    if (actual !== s.sha256) {
      fails.push(`${name}: ${s.file} hash mismatch — edited by hand? (run \`make docs-shots\`)`);
    }
  }
  if (!Object.keys(m.surfaces ?? {}).length) fails.push("manifest lists no surfaces");
}

if (fails.length) {
  console.error("docs-check FAILED:");
  for (const f of fails) console.error("  - " + f);
  process.exit(1);
}
console.log("docs-check ok: images match the current UI tree");
