import assert from "node:assert/strict";
import test from "node:test";
import { ageInDays, invisibleTopics, parseNote, parseSections, parseTopicFile, render } from "./handoff-board.mjs";

// ADR-0123: the board is assembled, so the assembly is what needs tests — the
// parsing of what sessions write, the attribution, the note age window and the
// budget that replaced the hand-kept cap.
const topic = `# Terminal

Intro prose that must not reach the board.

## Next

- Tab strip: keyboard close of \`.mtab-close\`
  continues on the next line.
- Live needs-you arrow

## Debts

- Terminal menus: web/mobile rows still offer only Remove.
`;

const note = `# 2026-09-12 — feat/settings-layers: Pi Settings

Shipped: prose.

## Next up

- Physical keyboard spot-check on the tablet

## Debts

- The pane tab resets the sub-tab (plain navigation).
`;

test("sections are parsed by heading name, continuation lines joined", () => {
  const s = parseSections(topic);
  assert.deepEqual(s.next, ["Tab strip: keyboard close of `.mtab-close` continues on the next line.", "Live needs-you arrow"]);
  assert.deepEqual(s.debts, ["Terminal menus: web/mobile rows still offer only Remove."]);
});

test("heading names are matched loosely, and prose is not a bullet", () => {
  const s = parseSections(note);
  assert.deepEqual(s["next up"], ["Physical keyboard spot-check on the tablet"]);
  assert.deepEqual(s.debts, ["The pane tab resets the sub-tab (plain navigation)."]);
  assert.equal(Object.values(s).flat().some((b) => b.includes("Shipped: prose")), false);
});

test("a topic file carries its title, a note its date and branch", () => {
  const t = parseTopicFile(topic, "terminal");
  assert.equal(t.title, "Terminal");
  assert.equal(t.next.length, 2);

  const n = parseNote(note, "2026-09-12-settings-layers.md");
  assert.equal(n.date, "2026-09-12");
  assert.equal(n.branch, "settings-layers");
});

// ADR-0140 supersedes ADR-0131's "debts are durable": a session note is
// transient, so its Debts leave the board with its Next after 7 days (ADR-0145). A
// debt that still matters past that belongs in docs/handoff/open/<topic>.md;
// the note's own text stays in git either way.
test("a note is a handoff, not a ledger: it leaves the board after 7 days", () => {
  const now = Date.parse("2026-09-12T12:00:00Z");
  // Five days old: still a handoff for whoever picks the work up.
  const recent = parseNote(`# 2026-09-10 — recent\n\n## Next up\n\n- fresh idea\n`, "2026-09-10-recent.md");
  assert.match(render({ worktrees: [{ isRoot: true }], topics: [], notes: [recent], now }).text, /fresh idea/);
  const old = parseNote(`# 2026-01-01 — stale\n\n## Next up\n\n- old idea\n\n## Debts\n\n- old debt\n`, "2026-01-01-stale.md");
  const { text } = render({ worktrees: [{ isRoot: true }], topics: [], notes: [old], now, idleHours: 24 });
  assert.doesNotMatch(text, /old debt/);
  assert.doesNotMatch(text, /old idea/);
  assert.match(text, /Nothing declared\. Add a `## Next` bullet/);
  assert.equal(ageInDays("2026-01-01", now) > 30, true);
});

test("every bullet is attributed to the file that owns it", () => {
  const now = Date.parse("2026-09-12T12:00:00Z");
  const { text, stats } = render({
    worktrees: [
      { isRoot: true, branch: "main", ahead: 0, behind: 0, dirty: 0, lastCommitAt: now },
      { isRoot: false, branch: "feat/x", ahead: 2, behind: 0, dirty: 1, lastCommitAt: now, greenAt: now, greenNow: true },
    ],
    topics: [parseTopicFile(topic, "terminal")],
    notes: [parseNote(note, "2026-09-12-settings-layers.md")],
    now,
    idleHours: 24,
  });
  assert.match(text, /^- Tab strip: keyboard close of `\.mtab-close` continues on the next line\. — \*terminal\*$/m);
  assert.match(text, /1 open debt\(s\) — \*terminal\* — open `docs\/handoff\/open\/terminal.md`/);
  assert.match(text, /Physical keyboard spot-check on the tablet — \*2026-09-12-settings-layers\*/);
  assert.match(text, /The pane tab resets the sub-tab \(plain navigation\)\. — \*2026-09-12-settings-layers\*/);
  assert.match(text, /`feat\/x` — 2 ahead, 0 behind, 1 dirty file\(s\), last commit just now, gates green just now/);
  assert.match(text, /do not edit this file/);
  assert.doesNotMatch(text, /Intro prose/);
  assert.ok(stats.lines < 100);
});

// ADR-0145: the view is bounded by construction. A topic with 130 bullets
// renders two of them plus a pointer, and the render never fails on size — the
// targets below can only warn, which is what the old cap got wrong (the only
// way to meet it was deleting another session's prose).
test("a topic longer than its quota truncates with a pointer, and still renders", () => {
  const bullets = Array.from({ length: 130 }, (_, i) => `- step ${i}`);
  const big = parseTopicFile(`# Big\n\n## Next\n\n${bullets.join("\n")}\n`, "big");
  const small = parseTopicFile(topic, "terminal");
  const { text, stats } = render({ worktrees: [{ isRoot: true }], topics: [big, small], notes: [], now: Date.now() });
  assert.ok(stats.lines <= 120, `expected <= 120 lines, got ${stats.lines}`);
  assert.ok(stats.bytes <= 12 * 1024, `expected <= 12 KB, got ${stats.bytes}`);
  assert.match(text, /^- step 0 — \*big\*$/m);
  assert.match(text, /^- step 1 — \*big\*$/m);
  assert.doesNotMatch(text, /^- step 2 — \*big\*$/m);
  assert.match(text, /…\+128 more in `docs\/handoff\/open\/big\.md`/);
  assert.ok(stats.hidden >= 128, `expected the hidden count, got ${stats.hidden}`);
});

// One verbose topic cannot blow the view up at all: the quota is per topic, so
// there is nothing to warn about and nothing to trim by hand.
test("one verbose topic is not an overflow", () => {
  const bullets = Array.from({ length: 400 }, (_, i) => `- step ${i}`);
  const big = parseTopicFile(`# Big\n\n## Next\n\n${bullets.join("\n")}\n`, "big");
  const { text, over, stats } = render({ worktrees: [{ isRoot: true }], topics: [big], notes: [], now: Date.now() });
  assert.ok(text.includes("# Handoff"));
  assert.deepEqual(over, []);
  assert.ok(stats.lines < 120);
});

// What can still grow is the number of *sources*. Then the generator names the
// biggest and writes anyway: `make close` is never blocked by how much the team
// wrote down, which is what the old cap got wrong.
test("many topics warn by name and still render", () => {
  const topics = Array.from({ length: 200 }, (_, i) => parseTopicFile(`# T${i}\n\n## Next\n\n- a step\n- another\n\n## Debts\n\n- a debt\n`, `t${i}`));
  const { text, over, stats } = render({ worktrees: [{ isRoot: true }], topics, notes: [], now: Date.now() });
  assert.ok(text.includes("# Handoff"));
  assert.ok(over.length > 0);
  assert.ok(stats.lines > 120);
});

// ADR-0131 A: a file whose bullets are all outside the two headings used to
// vanish from the board without a word. It names the file now.
test("a fully invisible topic file is refused, by name", () => {
  const orphan = parseTopicFile(`# Snippets — open debts\n\n- a debt nobody can see\n- another\n`, "snippets");
  assert.equal(orphan.bullets, 2);
  assert.equal(orphan.visible, 0);
  assert.deepEqual(invisibleTopics([orphan, parseTopicFile(topic, "terminal")]), ["snippets"]);

  // A file with its own extra sections is fine: only the two headings are the
  // board's business, the rest is deliberate (Traps, Slice 3, …).
  const mixed = parseTopicFile(`# Mixed\n\n## Next\n\n- a real next step\n\n## Traps (keep them paid)\n\n- a trap\n`, "mixed");
  assert.equal(mixed.visible, 1);
  assert.equal(mixed.bullets, 2);
  assert.deepEqual(invisibleTopics([mixed]), []);
});

// ADR-0131 C: the board carries the count and the plan, not the debt bullets.
test("debts render as a per-topic ledger with its plan", () => {
  const t = parseTopicFile(`# Terminal\n\n## Debts\n\n- a debt\n- another debt\n\nPlan: docs/plans/terminal.md\n`, "terminal");
  const { text } = render({ worktrees: [{ isRoot: true }], topics: [t], notes: [], now: Date.now() });
  assert.match(text, /2 open debt\(s\) — \*terminal\* — open `docs\/handoff\/open\/terminal.md` — Plan: `docs\/plans\/terminal.md`/);
  assert.doesNotMatch(text, /^- a debt$/m);
});
