// Run against an isolated picode-docs-fixture; only llama endpoints are mocked.
// PICODE_PLAYWRIGHT_MODULE points to an externally installed Playwright module.
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
const { chromium } = await import(process.env.PICODE_PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PICODE_QA_BASE || 'http://127.0.0.1:18763';
const fleet = await fetch(base + '/api/workspaces').then(r => r.json());
assert.ok((Array.isArray(fleet) ? fleet : fleet.workspaces).some(w => /^\/tmp\/picode-docs-fixture-/.test(w.path)), 'isolated fixture required');
const browser = await chromium.launch({ headless: true, ...(process.env.PICODE_QA_CHROME ? { executablePath: process.env.PICODE_QA_CHROME } : {}) });
const out = process.env.PICODE_QA_OUT || 'docs/screenshots';
mkdirSync(out, { recursive: true });
const evidence = { checks: [], screenshots: [], audits: [] };
try {
for (const app of ['desktop', 'mobile']) {
 const context = await browser.newContext({ viewport: app === 'desktop' ? { width: 1440, height: 900 } : { width: 390, height: 844 } });
 await context.addInitScript(() => localStorage.setItem("picode-theme", "dark"));
 const page = await context.newPage();
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 let code = 'ready', models = [], requests = [], jobs = [];
 await page.route('**/api/llama/jobs', r => r.fulfill({json:{jobs}}));
 await page.route('**/api/llama', r => r.fulfill({ json: { url: 'http://127.0.0.1:8080', ok: code === 'ready', models, connection: { code, message: code === 'ready' ? 'Connected' : code === 'authentication' ? 'The server rejected the API key.' : 'Cannot reach the server from PiCode.' } } }));
 await page.route('**/api/llama/load', async r => { requests.push(r.request().postDataJSON()); models = models.map(m => ({...m, status: 'loaded'})); jobs = [{ id: 'load-job', model: requests.at(-1).id, operation:'load', state:'succeeded', createdAt:new Date().toISOString(), endpoint:'http://127.0.0.1:8080' }]; await r.fulfill({ json: { job: jobs[0] } }); });
 await page.route('**/api/llama/unload', async r => { requests.push(r.request().postDataJSON()); models = models.map(m => ({...m, status:'unloaded'})); jobs = [{ id:'unload-job', model:requests.at(-1).id, operation:'unload', state:'succeeded', createdAt:new Date().toISOString(), endpoint:'http://127.0.0.1:8080' }]; await r.fulfill({json:{job:jobs[0]}}); });
 await page.route('**/api/providers/llama.cpp', async r => { requests.push(r.request().postDataJSON()); await r.fulfill({ json: { ok: true } }); });
 await page.route('**/api/llama/hf?*', r => r.fulfill({ json: { hits: [] } }));
 async function shot(name) {
   await page.evaluate(() => document.fonts.ready);
   await page.waitForTimeout(650);
   const audit = await page.evaluate(() => window.__picodeOverlayAudit());
   assert.equal(audit.ok, true, JSON.stringify(audit));
   const file = `llama-${app}-${name}.png`;
   await page.screenshot({ path: out + '/' + file });
   evidence.screenshots.push(file); evidence.audits.push({ file, ...audit });
 }
 await page.goto(base + `/${app}/#/providers/llama`);
 if (app === 'desktop') await page.locator('aside').first().getByText('Atlas', { exact: true }).waitFor();
 const manager = page.locator('#llama-manager');
 await manager.getByText('No models yet.', { exact: false }).waitFor();
 assert.ok(page.url().endsWith('#/llama/models'));
 await shot('empty');
 await manager.getByRole('button', { name: 'Download model', exact: true }).click();
 await page.getByRole('dialog').waitFor();
 await shot('download');
 await page.getByRole('dialog').getByRole('button', { name: 'Search', exact: true }).click();
 await page.getByText('No matching models.', { exact: false }).waitFor();
 await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click();
 await page.getByRole('dialog').waitFor({ state: 'hidden' });
 code = 'unreachable';
 await manager.getByRole('button', { name: 'Test connection' }).click();
 await manager.getByRole('link', { name: 'Configure server' }).waitFor();
 await shot('blocked');
 await manager.getByRole('link', { name: 'Configure server' }).click();
 code = 'authentication';
 await manager.getByRole('button', { name: 'Test connection' }).click();
 await manager.getByText('The server rejected the API key.').waitFor();
 await shot('error');
 await manager.getByLabel('Server URL', { exact: true }).fill('invalid');
 await manager.getByRole('button', { name: 'Save connection' }).click();
 await manager.getByRole('alert').waitFor(); assert.equal(requests.length, 0);
 await manager.getByLabel('Server URL', { exact: true }).fill('http://127.0.0.1:8081');
 code = 'ready';
 await manager.getByRole('button', { name: 'Save connection' }).click();
 await manager.getByText('Connected', { exact: true }).waitFor();
 assert.equal(requests[0].key, ''); assert.equal(requests[0].url, 'http://127.0.0.1:8081');
 models = [{ id:'Example/model-Q4_K_M', status:'loaded' }, { id:'Example/second-model-Q8_0', status:'unloaded' }];
 await manager.getByRole('link', { name: 'Models', exact: true }).click();
 await manager.getByRole('button', { name:'Test connection' }).click();
 await manager.getByText('Example/second-model-Q8_0', { exact:true }).waitFor();
 await shot('models');
 const before = requests.length;
 await manager.getByRole('button', { name:'Load', exact:true }).click();
 await page.locator('.dlg:visible').waitFor();
 await shot('replace');
 await page.locator('.dlg:visible').getByRole('button', { name:'Cancel', exact:true }).click();
 assert.equal(requests.length,before);
 await manager.getByRole('button', { name:'Load', exact:true }).click();
 await page.locator('.dlg:visible').getByRole('button', { name:'Load model', exact:true }).click();
 await page.waitForFunction(() => !document.querySelector('.llama-working'));
 assert.equal(requests.at(-1).unloadOthers,false);
 models[1].status = 'unloaded';
 await manager.getByRole('button', { name:'Test connection' }).click();
 await manager.getByRole('button', { name:'Load', exact:true }).click();
 await page.locator('.dlg:visible').getByRole('checkbox').check();
 await page.locator('.dlg:visible').getByRole('button', { name:'Load model', exact:true }).click();
 await page.locator('.dlg:visible').waitFor({state:'hidden'});
 await page.waitForFunction(() => !document.querySelector('.llama-working'));
 assert.equal(requests.at(-1).unloadOthers,true);
 await manager.getByRole('button', { name:'Test connection' }).click();
 await manager.getByRole('button', {name:'Unload',exact:true}).first().click();
 await page.locator('.dlg:visible').getByRole('button', {name:'Unload',exact:true}).click();
 await page.locator('.dlg:visible').waitFor({state:'hidden'});
 await page.waitForFunction(() => !document.querySelector('.llama-working'));
 assert.equal(requests.at(-1).id,'Example/model-Q4_K_M');

 await page.evaluate(() => document.documentElement.dataset.theme = 'light');
 await shot('light');
 assert.deepEqual(errors, []);
 evidence.checks.push(`${app}: legacy routing, empty/download/search, blocked/error, validation, credential save, cancel without mutation, load keeping others, light theme`);
 await page.goto(base + `/${app}/#/providers`);
 const entry = page.getByRole('link', { name: /^(Manage|Set up llama.cpp)$/ }).first();
 await entry.waitFor(); await entry.scrollIntoViewIfNeeded();
 await shot('providers');
 await entry.click();
 await page.locator('#llama-manager').waitFor();
 evidence.checks.push(`${app}: Providers entry opens manager`);
 await context.close();
}
writeFileSync(out + '/llama-qa.json', JSON.stringify(evidence, null, 2) + '\n');
console.log(JSON.stringify(evidence, null, 2));
} finally { await browser.close(); }
