//go:build windows

package desktop

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

// TestMain doubles as a disposable tray-shaped process for the real scheduler.
// Only a copy in a test directory containing its control file accepts --tray.
// It never imports the production tray or starts WSL.
func TestMain(m *testing.M) {
	if len(os.Args) == 2 && os.Args[1] == "--tray" {
		exe, err := os.Executable()
		if err != nil {
			os.Exit(10)
		}
		dir := filepath.Dir(exe)
		control := filepath.Join(dir, "picode-task-test-control")
		if _, err := os.Stat(control); err != nil {
			os.Exit(11)
		}
		log, err := os.OpenFile(filepath.Join(dir, "runs.log"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
		if err != nil {
			os.Exit(12)
		}
		_, _ = fmt.Fprintf(log, "%d\n", os.Getpid())
		_ = log.Close()
		deadline := time.Now().Add(4 * time.Minute)
		for time.Now().Before(deadline) {
			command, _ := os.ReadFile(control)
			switch string(command) {
			case "quit":
				os.Exit(0)
			case "crash":
				os.Exit(1)
			}
			time.Sleep(100 * time.Millisecond)
		}
		os.Exit(13)
	}
	os.Exit(m.Run())
}

type nativeTaskRunner struct{}

func (nativeTaskRunner) Output(name string, args ...string) ([]byte, error) {
	cmd := exec.Command(name, args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		err = fmt.Errorf("%w: %s", err, DecodeWindows(stderr.Bytes()))
	}
	return out, err
}

func (r nativeTaskRunner) Run(name string, args ...string) error {
	_, err := r.Output(name, args...)
	return err
}

func psLiteral(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

func taskNativeScript(t *testing.T, name, script string) []byte {
	t.Helper()
	if !strings.HasPrefix(name, "PiCodeDesktop-test-") {
		t.Fatal("native tests must not address the installed task")
	}
	preamble := "$ErrorActionPreference = 'Stop'; [Console]::OutputEncoding = [Text.UTF8Encoding]::new($false); " +
		"$service = New-Object -ComObject Schedule.Service; $service.Connect(); " +
		"$folder = $service.GetFolder('\\'); $name = " + psLiteral(name) + "; "
	out, err := (nativeTaskRunner{}).Output("powershell.exe", "-NoProfile", "-NonInteractive", "-Command", preamble+script)
	if err != nil {
		t.Fatalf("native task operation: %v: %s", err, out)
	}
	return out
}

func registerTaskCleanup(t *testing.T, name string) {
	t.Helper()
	t.Cleanup(func() {
		// This exact task was generated by this test. DeleteTask does not affect
		// other tasks; Stop ends only this task's disposable helper process.
		taskNativeScript(t, name, "$task = $folder.GetTask($name); $task.Stop(0); $folder.DeleteTask($name, 0)")
	})
}

func taskPreservedFields(t *testing.T, name string) map[string]string {
	t.Helper()
	out := taskNativeScript(t, name, "$x = [xml]$folder.GetTask($name).Xml; "+
		"@{principals=$x.Task.Principals.OuterXml; triggers=$x.Task.Triggers.OuterXml; actions=$x.Task.Actions.OuterXml; enabled=$x.Task.Settings.Enabled} | ConvertTo-Json -Compress")
	var fields map[string]string
	if err := json.Unmarshal([]byte(DecodeWindows(out)), &fields); err != nil {
		t.Fatal(err)
	}
	return fields
}

func TestWindowsTaskPolicyRoundTrip(t *testing.T) {
	name := "PiCodeDesktop-test-" + rand.Text()
	// A path containing spaces, an apostrophe and non-ASCII characters must
	// survive Go -> PowerShell -> COM without becoming executable script text.
	exe := filepath.Join(t.TempDir(), "PiCode O'Brien 工具.exe")
	if err := os.WriteFile(exe, []byte("not launched by this test"), 0o600); err != nil {
		t.Fatal(err)
	}
	r := nativeTaskRunner{}
	s, err := taskOperation(r, "install", name, exe)
	if err != nil {
		t.Fatal(err)
	}
	registerTaskCleanup(t, name)
	if issues := s.PolicyIssues(); len(issues) != 0 || !s.Enabled || s.Executable != exe {
		t.Fatalf("installed task = %+v, issues = %v", s, issues)
	}
	// Recreate the old Windows defaults, plus a user opt-out. No process runs.
	taskNativeScript(t, name, "$d = $folder.GetTask($name).Definition; "+
		"$d.Settings.ExecutionTimeLimit = 'PT72H'; $d.Settings.DisallowStartIfOnBatteries = $true; "+
		"$d.Settings.StopIfGoingOnBatteries = $true; $d.Settings.IdleSettings.StopOnIdleEnd = $true; "+
		"$d.Settings.RunOnlyIfNetworkAvailable = $true; $d.Settings.MultipleInstances = 0; "+
		"$d.Settings.RestartCount = 0; $d.Settings.RestartInterval = ''; $d.Settings.Enabled = $false; "+
		"$folder.RegisterTaskDefinition($name, $d, 4, $null, $null, 3, $null) | Out-Null")
	before := taskPreservedFields(t, name)
	beforeXML := strings.TrimSpace(DecodeWindows(taskNativeScript(t, name, "$folder.GetTask($name).Xml")))
	s, err = repairTask(r, name)
	if err != nil {
		t.Fatal(err)
	}
	if len(s.PolicyIssues()) != 0 || s.Enabled || s.Backup == "" {
		t.Fatalf("repair did not preserve disabled choice/backup: %+v", s)
	}
	t.Cleanup(func() { _ = os.Remove(s.Backup) })
	backup, err := os.ReadFile(s.Backup)
	if err != nil || strings.TrimSpace(strings.TrimPrefix(DecodeWindows(backup), "\ufeff")) != beforeXML {
		t.Fatalf("previous definition was not backed up: %v", err)
	}
	if after := taskPreservedFields(t, name); !reflect.DeepEqual(before, after) {
		t.Fatalf("repair changed identity, triggers, action or enabled choice:\nbefore %v\nafter %v", before, after)
	}
	noChange, err := repairTask(r, name)
	if err != nil || noChange.Backup != "" {
		t.Fatalf("already-correct repair wrote again: %+v, %v", noChange, err)
	}
	// A named task alone is not authority to rewrite an unrelated command.
	taskNativeScript(t, name, "$d = $folder.GetTask($name).Definition; $d.Actions.Item(1).Arguments = 'version'; "+
		"$folder.RegisterTaskDefinition($name, $d, 4, $null, $null, 3, $null) | Out-Null")
	before = taskPreservedFields(t, name)
	if _, err := taskOperation(r, "repair", name, ""); err == nil {
		t.Fatal("write boundary accepted a non-tray action")
	}
	if after := taskPreservedFields(t, name); !reflect.DeepEqual(before, after) {
		t.Fatal("refused repair changed the task")
	}
	missing, err := taskOperation(r, "inspect", name+"-missing", "")
	if err != nil || missing.Exists {
		t.Fatalf("missing task: %+v, %v", missing, err)
	}
	if _, err := taskOperation(r, "repair", name+"-missing", ""); err == nil {
		t.Fatal("repair created a missing task")
	}
}

func TestWindowsTaskLaunchRetryAndQuit(t *testing.T) {
	if os.Getenv("PICODE_TEST_TASK_LIFECYCLE") != "1" {
		t.Skip("manual native acceptance (over two minutes): docs/plans/desktop-task-reliability.md#validation")
	}
	dir := t.TempDir()
	self, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(self)
	if err != nil {
		t.Fatal(err)
	}
	exe := filepath.Join(dir, "picode-task-fixture.exe")
	if err := os.WriteFile(exe, content, 0o700); err != nil {
		t.Fatal(err)
	}
	control := filepath.Join(dir, "picode-task-test-control")
	writeCommand := func(command string) {
		t.Helper()
		if err := os.WriteFile(control, []byte(command), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	writeCommand("wait")
	name := "PiCodeDesktop-test-" + rand.Text()
	r := nativeTaskRunner{}
	if _, err := taskOperation(r, "install", name, exe); err != nil {
		t.Fatal(err)
	}
	registerTaskCleanup(t, name)
	runs := func() int {
		data, _ := os.ReadFile(filepath.Join(dir, "runs.log"))
		return len(strings.Fields(string(data)))
	}
	waitFor := func(label string, timeout time.Duration, condition func() bool) {
		t.Helper()
		deadline := time.Now().Add(timeout)
		for time.Now().Before(deadline) {
			if condition() {
				return
			}
			time.Sleep(250 * time.Millisecond)
		}
		t.Fatalf("timed out: %s", label)
	}
	// RestartOnFailure covers failure to start an action, not arbitrary
	// nonzero exits of an already-started process (MS-TSCH 2.5.4.2). Make
	// only this test's executable temporarily unavailable at a timed start.
	if err := os.Rename(exe, exe+".unavailable"); err != nil {
		t.Fatal(err)
	}
	taskNativeScript(t, name, "$d = $folder.GetTask($name).Definition; "+
		"$trigger = $d.Triggers.Create(1); $trigger.StartBoundary = [DateTime]::Now.AddSeconds(5).ToString('s'); "+
		"$trigger.ExecutionTimeLimit = 'PT0S'; $trigger.Enabled = $true; "+
		"$folder.RegisterTaskDefinition($name, $d, 4, $null, $null, 3, $null) | Out-Null")
	waitFor("missing executable result", 20*time.Second, func() bool {
		s, err := taskOperation(r, "inspect", name, "")
		return err == nil && uint32(s.LastResult) == 0x80070002
	})
	if runs() != 0 {
		t.Fatal("unavailable executable unexpectedly ran")
	}
	if err := os.Rename(exe+".unavailable", exe); err != nil {
		t.Fatal(err)
	}
	t.Log("launch failure observed; executable restored for the scheduler retry")
	waitFor("launch retry", 90*time.Second, func() bool { return runs() == 1 })
	t.Log("scheduler launch retry recovered")
	taskNativeScript(t, name, "$folder.GetTask($name).Run($null) | Out-Null")
	time.Sleep(time.Second)
	if runs() != 1 {
		t.Fatal("IgnoreNew started a second process")
	}
	t.Log("single instance verified; asking the disposable helper to Quit with status zero")
	writeCommand("quit")
	waitFor("normal exit", 15*time.Second, func() bool {
		s, err := taskOperation(r, "inspect", name, "")
		return err == nil && s.State == 3 && s.LastResult == 0
	})
	// Observe beyond the configured restart interval, not just two happy clicks.
	deadline := time.Now().Add(70 * time.Second)
	for time.Now().Before(deadline) {
		if runs() != 1 {
			t.Fatal("normal Quit was restarted")
		}
		time.Sleep(500 * time.Millisecond)
	}
	t.Log("normal Quit remained stopped beyond the recovery interval")
	// A runtime failure is recorded, but no automatic restart is promised.
	writeCommand("wait")
	taskNativeScript(t, name, "$folder.GetTask($name).Run($null) | Out-Null")
	waitFor("manual restart after Quit", 15*time.Second, func() bool { return runs() == 2 })
	writeCommand("crash")
	waitFor("runtime failure recorded", 15*time.Second, func() bool {
		s, err := taskOperation(r, "inspect", name, "")
		return err == nil && s.State == 3 && s.LastResult == 1
	})
}
